---
# common rollback tasks file for 3tier_application

## RedHat Ansible Boot Camp homework assignment
## Playbook have been written as a PoC for a 3Tier Application deployment
## All playbook have been written via Ansible Core and used in Ansible Tower

## Created a written by Paul Greenbank - Technical Consultant for Open System Specialists

## Playbook description:
#
# Role is called via the Rollback_3TA_OSP playbook, it will rollback all common tasks which
# have been applied to all instances in the application stack
#

  - name: Remove Application software repos
    file:
      path: /etc/yum.repos.d/open_three-tier-app.repo
      state: absent
