---
## Configure and deploy 3Tier Application

## RedHat Ansible Boot Camp homework assignment
## Playbook have been written as a PoC for a 3Tier Application deployment
## All playbook have been written via Ansible Core and used in Ansible Tower

## Created a written by Paul Greenbank - Technical Consultant for Open System Specialists

## Playbook description:
#
# Playbook uses 3 configuration roles and a tagged in memory inventory role
# to configure the OpenStack instances.
# Inventory groups are created based on OpenStack meta tags used during instance deployment.
# The openstack_hosts role has been tagged so when deploying application into AWS
# this role can be excluded from the play in the Ansible Tower template using skip tags.
# The yum repo file is encrypted using ansible vault to protect it's contents while stored in
# public git repository.

## Playbook enhancements post PoC:
#
# Enhancements would be to remove the in memory inventory in favour of of setting up 
# a inventory using the OpenStack source
#

- hosts: jumpbox
  gather_facts: false
  roles:
    - { role: openstack_hosts, tags: openstack }

- name: Add yum repo for 3Tier application
  hosts: appsdb:apps:frontends
  gather_facts: true
  become: yes
  tasks:
    - name: Including common role
      include_role:
        name: 3tier_common

- name: Install Postgres for 3Tier application
  hosts: appsdb
  gather_facts: true
  become: yes
  tasks:
    - name: Including postgres role
      include_role:
        name: 3tier_postgres

- name: Install Tomcat for 3Tier application
  hosts: apps
  gather_facts: true
  become: yes
  tasks:
    - name: Including tomcat role
      include_role:
        name: 3tier_tomcat

- name: Install HAProxy for 3Tier application
  hosts: frontends
  gather_facts: true
  become: yes
  tasks:
    - name: Including haproxy role
      include_role:
        name: 3tier_haproxy
