---
# 3Tier Application cleanup / rollback playbook

- name: Remove yum repo for 3Tier application
  hosts: appsdb:apps:frontends
  tasks:
    - name: Including common role
      include_role:
        name: 3tier_common
        tasks_from: rollback_common

- name: Remove Postgres for 3Tier application
  hosts: appsdb
  tasks:
    - name: Including postgres role
      include_role:
        name: 3tier_postgres
        tasks_from: rollback_postgres

- name: Remove Tomcat for 3Tier application
  hosts: apps
  tasks:
    - name: Including tomcat role
      include_role:
        name: 3tier_tomcat
        tasks_from: rollback_tomcat

- name: Remove HAProxy for 3Tier application
  hosts: frontends
  tasks:
    - name: Including haproxy role
      include_role:
        name: 3tier_haproxy
        tasks_from: rollback_haproxy


