---

- hosts: all
  gather_facts: false
  roles:
    - openshift_hosts

- name: Check contents returned from HAProxy
  hosts: jumpbox
  gather_facts: false
  tasks:
    - name: Check URL content returned from first frontend HAProxy
      uri:
        url: http://{{ groups['frontends'][0] }}
        return_content: yes
      register: webpage

    - name: Fail if "Ansible has done its job" is not in the page content
      fail: mgs="Incorrect content returned from Proxy"
      when: "'Ansible has done its job' not in webpage.content"

- name: Check Postgres for 3Tier application
  hosts: appsdb
  gather_facts: false
  tasks:
    - name: Check Postgres service is Running
      command: systemctl status postgresql
      register: postgres

    - name: Fail if service status doesn't return "active (running)"
      fail: msg="PostgreSQL is not running"
      when: "'active (running)' not in postgres.stdout"
        
- name: Check Tomcat for 3Tier application
  hosts: apps
  gather_facts: true
  become: yes
  tasks:
    - name: Check Tomcat service is Running
      command: systemctl status tomcat
      register: tomcat

    - name: Fail if service status doesn't return "active (running)"
      fail: msg="Tomcat is not running"
      when: "'active (running)' not in tomcat.stdout"

    - name: Check Tomcat web content
      command: cat /usr/share/tomcat/webapps/ansible/index.html
      register: web_content

    - name: Fail if web content doesn't contain "Ansible has done its job"
      fail: msg="Incorrect web content on {{ ansible_hostname }}"
      when: "'Ansible has done its job' not in web_content.stdout"


