---
## RedHat Ansible Boot Camp homework assignment
## Playbook have been written as a PoC for a 3Tier Application deployment
## All playbook have been written via Ansible Core and used in Ansible Tower

## Created a written by Paul Greenbank - Technical Consultant for Open System Specialists

## Playbook description:
#
# Installs Tomcat package named in the variables file.
# Application directories are created if the are no created with the Tomcat install process
# this is to ensure that the necessary directory are present prior to installing the Tomcat
# content files.
# Tomcat application content files are then installed from two seperate html templates in which
# content is configured based on the tomcat backend server name.
#

## Playbook enhancements post PoC:
#
# Tomcat package install should be expanded to use items so that any extra dependencies can
# be added to the variables rather than having to alter the playbook.
#

# tasks file for 3tier_application tomcat role

  - name: install tomcat package
    yum:
      name: "{{ tomcat_package }}"
      state: latest
    notify:
      - enable tomcat service

  - name: create ansible tomcat web directories
    file:
      path: "{{ item }}"
      state: directory
    with_items: "{{ tomcat_webapps_directories }}"

  - name: copy static index.html to tomcat webapps/ROOT/index.html
    template:
      src: index.html.j2
      dest: /usr/share/tomcat/webapps/ROOT/index.html
      owner: root
      group: root
      mode: 0644
    notify:
      - restart tomcat service

  - name: copy static index.html to tomcat webapps/ansible/index.html
    template:
      src: index.html.app.j2
      dest: /usr/share/tomcat/webapps/ansible/index.html
    notify:
      - restart tomcat service

