---
# postgres rollback tasks file for 3tier_application

## RedHat Ansible Boot Camp homework assignment
## Playbook have been written as a PoC for a 3Tier Application deployment
## All playbook have been written via Ansible Core and used in Ansible Tower

## Created a written by Paul Greenbank - Technical Consultant for Open System Specialists

## Playbook description:
#
# Role is called via the Rollback_3TA_OSP playbook, it will rollback all tasks which
# have been applied to appsdb instances in the application stack
#

# Rollback postgres tasks file for 3tier_application

  - name: Remove postgres
    yum:
      name: "{{ postgres_package }}"
      state: absent

  - name: Remove postgres data
    file:
      path: /var/lib/pgsql/data
      state: absent

